### ISSUE TITLE
ERROR: Failed building wheel for gdal

### ISSUE THREAD

**Issue by ksandesh2** [danfenghong/ISPRS_HD-Net#1]
I'm getting this error:
![image](https://github.com/danfenghong/ISPRS_HD-Net/assets/72401200/521c769f-ecde-40a4-8630-fad0f15fc949); when i try to install osgeo package then I get this error: 
![image](https://github.com/danfenghong/ISPRS_HD-Net/assets/72401200/248e5f39-d58b-435b-ac59-eb5d6f5206bd)

**Comment by Xuaner624** [comment]
I recommend installing the gdal library using the "conda install gdal" command. Additionally, you can try downloading the latest wheel file from "https://github.com/cgohlke/geospatial-wheels/releases/tag/v2024.2.18" for installation, as the old gdal wheel download link is no longer available.

**Comment by Xuaner624** [comment]
You can also utilize "Image.open" to read TIF files. Just ensure to read labels within the 0-1 range.

**Comment by ksandesh2** [comment]
Thank you so much, professor! Inspired by your work!!

**Comment by ksandesh2** [comment]
Thank you so much, professor! Inspired by your work

**Comment by study006** [comment]
Could you please share the code for cropping and excluding images? Or is it possible to upload your processed dataset?
